### PR TITLE
added font-logo-mobile, added media query to Header styling

### PR DESCRIPTION
**Pull request by TyLippe**
## Description
Added a new variable named font-logo--mobile, set it to 1rem, then in Header.scss I created a media query under the title to decrease font size of the logo while also being responsive, 

Fixes#93

### CODE REVIEW

**Comment by SheaBelsky** [comment]
Is this the same issue as that in #93? Or what is the difference? Looks like it was the same MR.

**Comment by TyLippe** [comment]
Sorry about that, I am still learning how to work with Open Source, I misread the objective, I thought that issue was something that needed to be worked on.

**Comment by TyLippe** [comment]
I clicked #93, I now realize that this issue was #92 and has been closed.

**Comment by SheaBelsky** [comment]
I think we're good to close this PR, then. If you'd like to pick up another issue, please feel free to do so!

**Comment by TyLippe** [comment]
Will take a look! Thank you!

**Pull request closed without merging**
