### PR TITLE
Buttons small devices

### LINKED ISSUE #71: Buttons on small devices do not contain all of their content
**Describe the bug**
Buttons on smaller devices do not contain all of their content if there is a lot of it.

**To Reproduce**
1. View the Awesome Learning site on mobile (or Inspect Element and emulate a mobile device)
2. Go to https://wayfair.github.io/awesome-learning/courses/Testing/
3. Scroll to the bottom of the page

**Expected behavior**
Buttons should contain all of their contents, rather than having text overflow from the bottom of the button vertically. 

**Screenshots**
Screen Shot 2019-09-29 at 9 06 57 AM

**Additional context**
When implementing this fix, make sure our existing buttons are not affected!

### PR DESCRIPTION
**Pull request by Arnoldicus**
image

### CODE REVIEW

**Comment by SheaBelsky** [comment]
Thanks for picking up this issue! Could we accomplish this with just CSS, versus needing to pass in a `styles` object based on the number of words? The height of the button should automatically grow with its contents, versus needing to set the font size in response to the number of words it will contain.

**Comment by Arnoldicus** [comment]
@SheaBelsky okay, will do that

**Comment by Arnoldicus** [comment]
@SheaBelsky check if please

**Comment by SheaBelsky** [comment]
Great, how does this look on desktop devices? Could you post a screenshot of it?

**Comment by Arnoldicus** [comment]
@SheaBelsky 
image

**Comment by SheaBelsky** [comment]
Looks great to me! Thank you so much for picking this up!

**Pull request merged**
