### PR TITLE
Fixed Layout as 80% to big screen devices

### PR DESCRIPTION
**Pull request by shreegowtham27**

### CODE REVIEW

**Comment by SheaBelsky** [comment]
Thanks for picking up this issue! Could you unstage the changes you made to `package-lock.json`? Once you do, I'll approve this and merge it in!

**Comment by shreegowtham27** [comment]
Unstaged Package-lock.json file. Please Check. [SheaBelsky](https://github.com/SheaBelsky)

**Comment by SheaBelsky** [comment]
Can you post a screenshot of how this looks on the site with different screen sizes? Does the content remain centered even if the media query is active? Or do you need to add anything to center it (`margin: auto`)?

**Comment by shreegowtham27** [comment]
FYR  [SheaBelsky](https://github.com/SheaBelsky)

Desktop View

image

Mobile View

screenshot-localhost_8000-2019 10 11-10_33_03

**Comment by SheaBelsky** [comment]
Thank you for picking up this issue @shreegowtham27 !

**Pull request merged**
