### PR TITLE
Change theme color for mobile devices

### PR DESCRIPTION
**Pull request by pyymenta**
## Description

* It Changes the browser color for mobile devices.

## Screenshots

BEFORE

image

AFTER 

chrome-capture

## Changelog

* Change theme color(same as header) 258d36e
* Remove top-border e0a5ccf

## Related Issues

#77

### CODE REVIEW

**Comment by SheaBelsky** [comment]
Looks good to me! @Cooperbuilt Is this a good color for the browser? I realize now that we might want some color contrast between the browser and the top navigation. @pyymenta can we see how it looks with the hex value `#00a7ba` or `#455A81`? Just screenshots will do, you don't need to commit anything yet.

**Comment by pyymenta** [comment]
> Looks good to me! @Cooperbuilt Is this a good color for the browser? I realize now that we might want some color contrast between the browser and the top navigation. @pyymenta can we see how it looks with the hex value `#00a7ba` or `#455A81`? Just screenshots will do, you don't need to commit anything yet.

Yeah, of course!

With #00a7ba

image

With #455A81

image

Honestly, I prefer with #2A416E. Although #455A81 looks good to me too. What do you think?

**Comment by pyymenta** [comment]
> > Looks good to me! @Cooperbuilt Is this a good color for the browser? I realize now that we might want some color contrast between the browser and the top navigation. @pyymenta can we see how it looks with the hex value `#00a7ba` or `#455A81`? Just screenshots will do, you don't need to commit anything yet.
> 
> Yeah, of course!
> 
> With #00a7ba
> 
> image
> 
> With #455A81
> 
> image
> 
> Honestly, I prefer with #2A416E. Although #455A81 looks good to me too. What do you think?

Thinking about contrast, I think #455A81 is a better choose.

**Comment by Cooperbuilt** [comment]
I prefer the `#455A81` option

**Comment by SheaBelsky** [comment]
Looks like we have a consensus. @pyymenta can we use the version with `#455A81` and commit that? Then we'll get you merged in!

**Comment by pyymenta** [comment]
> Looks like we have a consensus. @pyymenta can we use the version with `#455A81` and commit that? Then we'll get you merged in!

Cool! I'll change it right now.

**Pull request merged**
