### PR TITLE
Removed React Test Renderer Dependency & Tests

### PR DESCRIPTION
**Pull request by Eshno**
## Description

Removed all tests using `react-test-renderer`.
Updated `package.json` and package-lock.json` by removing the `react-test-renderer` dependency.

## Related Issues

Issue: https://github.com/wayfair/awesome-learning/issues/59
Related: https://github.com/wayfair/awesome-learning/issues/21

Removed Files: 

```
src/components/Course/Course.test.js
src/components/Course/Tags/Tags.test.js
src/components/Courses/Courses.test.js
src/components/Header/Header.test.js
src/components/Header/Menu/Menu.test.js
src/components/Icon/Icon.test.js
src/components/Layout/Layout.test.js
src/components/Page/Page.test.js
src/components/Pagination/Pagination.test.js
src/components/SectionTitle.test.js
src/components/Text/Text.test.js
src/templates/categories-list-template.test.js
src/templates/category-template.test.js
src/templates/course-template.test.js
src/templates/index-template.test.js
src/templates/not-found-template.test.js
src/templates/page-template.test.js
src/templates/quiz-template.test.js
src/templates/tag-template.test.js
src/templates/tags-list-template.test.js
```
Removed SnapShots: 

```
src/components/Course/Tags/__snapshots__/Tags.test.js.snap
src/components/Course/__snapshots__/Course.test.js.snap
src/components/Courses/__snapshots__/Courses.test.js.snap
src/components/Icon/__snapshots__/Icon.test.js.snap
src/components/Layout/__snapshots__/Layout.test.js.snap
src/components/Page/__snapshots__/Page.test.js.snap
src/components/Pagination/__snapshots__/Pagination.test.js.snap
src/templates/__snapshots__/categories-list-template.test.js.snap
src/templates/__snapshots__/category-template.test.js.snap
src/templates/__snapshots__/course-template.test.js.snap
src/templates/__snapshots__/index-template.test.js.snap
src/templates/__snapshots__/not-found-template.test.js.snap
src/templates/__snapshots__/page-template.test.js.snap
src/templates/__snapshots__/quiz-template.test.js.snap
src/templates/__snapshots__/tag-template.test.js.snap
src/templates/__snapshots__/tags-list-template.test.js.snap
```

### CODE REVIEW

**Comment by SheaBelsky** [comment]
@Eshno Can you resolve your merge conflicts? I'm not sure why the build is not kicking off, it might be due to the merge conflicts.

**Comment by Eshno** [comment]
@SheaBelsky Solved merge conflicts by now!

**Comment by Eshno** [comment]
I'd appreciate that, Thank you!

**Comment by Cooperbuilt** [comment]
Nice work cleaning up all the snapshots as well! Merging in. Thank you for the contribution and happy hacking!

**Pull request merged**
