### PR TITLE
Shared components

### PR DESCRIPTION
**Pull request by juancarlosqr**
## Description

Moves several shared components to its own folder under `components/shared`. Affects the following components:

- Block
- ContentSection
- Icon
- Layout
- Link
- Page
- SectionTitle
- Text

Additionally I fix inconsistencies regarding single/double quotes among the components I needed to change as part of the relocation task

## Related Issues

Addresses #50

### CODE REVIEW

**Comment by juancarlosqr** [comment]
@Cooperbuilt just to let you know you got a PR here ;-)

**Comment by Cooperbuilt** [comment]
I'm ready to merge it in! Sorry for the delay work got a little crazy there for a few days. Looks like there are a few merge conflicts (sorry about that). Once those are fixed I will get this merged right in for you. Thank you again for taking this on @juancarlosqr!

**Comment by juancarlosqr** [comment]
No problem at all! Glad to have contributed. Nice codebase

**Comment by Cooperbuilt** [comment]
Thanks @juancarlosqr - just ping me when you are ready and I will get it merged in.

**Comment by juancarlosqr** [comment]
> Thanks @juancarlosqr - just ping me when you are ready and I will get it merged in.

Can you let me know what should I do next? Not sure actually....

My feelings is: merge your master into my forked branch to resolve the conflicts and push the changes right?

**Comment by Cooperbuilt** [comment]
Yep exactly!

**Comment by juancarlosqr** [comment]
@Cooperbuilt you're good to go!

**Comment by Cooperbuilt** [comment]
Nice! Thank you for all the hard work on this one and we hope to see you around on another pr someday 👍

**Comment by juancarlosqr** [comment]
@Cooperbuilt my pleasure, thanks. Glad to have contributed

**Pull request merged**
