### PR TITLE
Excessive space on some pages for small devices > bug fixed #72

### LINKED ISSUE #72: Excessive space on some pages for small devices
**Describe the bug**
On small devices, there is an excessive amount of space between the last of the content and the actual end of the page.

**To Reproduce**
1. Go to any page on mobile (https://wayfair.github.io/awesome-learning/courses/Testing/testing-workshop/)
2. Scroll to the bottom of the page

**Expected behavior**
The end of the page should be much closer to the actual end of the page, rather than there being an excessive amount of space

**Screenshots**
Screen Shot 2019-09-29 at 9 11 27 AM

**Additional context**
We want a small amount of space at the end of the page, but not as much as there is. When you create a PR to fix this issue, include a screenshot of what the new amount of space is.

### PR DESCRIPTION
**Pull request by Arnoldicus**
image

### CODE REVIEW

**Comment by SheaBelsky** [comment]
Thanks for taking this on! Does it still look good on desktop? Can you post a screenshot of what that looks like?

**Comment by Arnoldicus** [comment]
@SheaBelsky sure
image

**Comment by SheaBelsky** [comment]
Is that drop shadow at the bottom of the page from your browser? Or is it actually there on the page?

**Comment by Arnoldicus** [comment]
@SheaBelsky there is no shadow on styles. u can check it if you open on full screen

**Comment by SheaBelsky** [comment]
Cool, just wanted to make sure since I saw it in the screenshot! You're all set!

**Pull request merged**
