### PR TITLE
Fix and remove unused icons

### PR DESCRIPTION
**Pull request by YogaSakti**
## Description

* Change the Octocat icon, from the tail on the left to the right. 
* Remove unused icon (vkontakte, telegram, rss).

## Related Issues

This Pr related to #70

### CODE REVIEW

**Comment by YogaSakti** [comment]
by the way, I can't run npm develop because there's a problem in scss.

**Comment by Cooperbuilt** [comment]
can you pull master and try again? We updated a few things

**Comment by YogaSakti** [comment]
already pull master but still gets the same error.

image

**Comment by SheaBelsky** [comment]
I just pulled your fork and was able to run `npm run develop; npm run lint; npm run build` without any issues. Can you do a fresh `npm install` on your fork and then run those commands?

**Comment by Cooperbuilt** [comment]
Any updates @YogaSakti?

**Comment by SheaBelsky** [comment]
Resolved by #98

**Pull request closed without merging**
