### PR TITLE
Issue #92 : Added scalable class for logo on mobile devices

### PR DESCRIPTION
**Pull request by smcveigh941**
## Description

Added a scalable font-size attribute to the Header-title class so that the logo is scaled on mobile devices

## Related Issues

Issue #92

### CODE REVIEW

**Comment by smcveigh941** [comment]
Hi @Cooperbuilt,

Thanks for the review. If I have understood you correctly, I have carried out the changes requested. 

What should we do with `font--small` and `font--xl`? They do have a few usages

**Comment by Cooperbuilt** [comment]
Oh man, thank you for taking this on! For the small and xl, we could carry out the same naming convention and do something like 
```
$font--500: .875rem;
$font--1000: 1rem;
$font--1500: 1.25rem;
$font--2000: 1.5rem;
$font--2500: 1.75rem;
$font--3000: 2rem;
$font--3500: 2.5rem;
```

**Comment by smcveigh941** [comment]
@Cooperbuilt here you are :) I can see that the issue of the logo not scaling for mobile devices has been addressed in another PR that has already been merged here 

https://github.com/wayfair/awesome-learning/pull/93

I have rebased with the latest master since that. This PR now just serves the purpose of refactoring variable names :)

**Comment by Cooperbuilt** [comment]
@smcveigh941 Thank you! I really appreciate the work you did here and we welcome any other contributions you may be interested in. Happy hacking!

**Pull request merged**
