### PR TITLE
Added sorting to courses list

### PR DESCRIPTION
**Pull request by jaysiee**
Signed-off-by: Johannes Siebel <johannes.siebel@gmail.com>

## Description

Added a call to the sort() method upon rendering the list of courses.

## Related Issues

https://github.com/wayfair/awesome-learning/issues/69

### CODE REVIEW

**Comment by SheaBelsky** [comment]
Hey, thanks for picking up this issue! Is it possible for this sort to be done at the GraphQL level, versus in JavaScript? That way the sorting is done at compile/deploy time, rather than every time someone visits the page.

https://www.gatsbyjs.org/docs/graphql-reference/#sort

Make sure to touch with @BalSharma, I know they wanted to work on this too.

**Comment by jaysiee** [comment]
@SheaBelsky Fair point, should've done that in the first place. I've changed my PR to actually do that.

**Comment by SheaBelsky** [comment]
Awesome! A few people have asked me to wait until October 1st to merge stuff in for Hacktoberfest. Do you want to wait until then, or is OK to merge this in now?

**Comment by jaysiee** [comment]
If you don't mind waiting, I'd gladly take this as my first PR for Hacktober.

**Pull request merged**
